<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="12" total="46" passed="32">
  <reporter-output>
  </reporter-output>
  <suite name="Selenium-Test-cases" duration-ms="14772" started-at="2023-02-13T03:08:47Z" finished-at="2023-02-13T03:09:02Z">
    <groups>
    </groups>
    <test name="testFactory" duration-ms="104" started-at="2023-02-13T03:08:47Z" finished-at="2023-02-13T03:08:47Z">
      <class name="FactoryImplTestSubtract">
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:FactoryImplTestSubtract@2e1af49b]" name="initCalculator" is-config="true" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:FactoryImplTestSubtract@2e1af49b]" name="initCalculator" is-config="true" duration-ms="2" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
        <test-method status="FAIL" signature="testSubtract()[pri:0, instance:FactoryImplTestSubtract@2e1af49b]" name="testSubtract" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at FactoryImplTestSubtract.testSubtract(FactoryImplTestSubtract.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSubtract -->
        <test-method status="PASS" signature="testSubtract()[pri:0, instance:FactoryImplTestSubtract@7de843ef]" name="testSubtract" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSubtract -->
      </class> <!-- FactoryImplTestSubtract -->
      <class name="FactoryImplTestAdd">
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:FactoryImplTestAdd@7e4d2287]" name="initCalculator" is-config="true" duration-ms="15" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:FactoryImplTestAdd@7e4d2287]" name="initCalculator" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
        <test-method status="PASS" signature="testAdd()[pri:0, instance:FactoryImplTestAdd@74075134]" name="testAdd" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdd -->
        <test-method status="FAIL" signature="testAdd()[pri:0, instance:FactoryImplTestAdd@7e4d2287]" name="testAdd" duration-ms="2" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [5] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [5] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at FactoryImplTestAdd.testAdd(FactoryImplTestAdd.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdd -->
        <test-method status="PASS" signature="testAdd()[pri:0, instance:FactoryImplTestAdd@b10a26d]" name="testAdd" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdd -->
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:FactoryImplTestAdd@7e4d2287]" name="initCalculator" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
      </class> <!-- FactoryImplTestAdd -->
    </test> <!-- testFactory -->
    <test name="testDataProvider" duration-ms="10" started-at="2023-02-13T03:08:47Z" finished-at="2023-02-13T03:08:47Z">
      <class name="DataProviderTest">
        <test-method status="PASS" signature="testDataProviderMethod(java.lang.String)[pri:0, instance:DataProviderTest@63bde6c2]" name="testDataProviderMethod" duration-ms="5" started-at="2023-02-13T08:38:47Z" data-provider="data-provider" finished-at="2023-02-13T08:38:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data one]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataProviderMethod -->
        <test-method status="PASS" signature="testDataProviderMethod(java.lang.String)[pri:0, instance:DataProviderTest@63bde6c2]" name="testDataProviderMethod" duration-ms="0" started-at="2023-02-13T08:38:47Z" data-provider="data-provider" finished-at="2023-02-13T08:38:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data two]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataProviderMethod -->
        <test-method status="PASS" signature="testDataProviderMethod(java.lang.String)[pri:0, instance:DataProviderTest@63bde6c2]" name="testDataProviderMethod" duration-ms="0" started-at="2023-02-13T08:38:47Z" data-provider="data-provider" finished-at="2023-02-13T08:38:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[data three]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataProviderMethod -->
      </class> <!-- DataProviderTest -->
    </test> <!-- testDataProvider -->
    <test name="testCaculate" duration-ms="5" started-at="2023-02-13T03:08:47Z" finished-at="2023-02-13T03:08:47Z">
      <class name="CalculatorTestSuccessful">
        <test-method status="PASS" signature="beforeEachTest()[pri:0, instance:CalculatorTestSuccessful@713064e8]" name="beforeEachTest" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeEachTest -->
        <test-method status="PASS" signature="testDivisionException()[pri:0, instance:CalculatorTestSuccessful@713064e8]" name="testDivisionException" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Divider can't be zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Divider can't be zero
	at utils.Calculator.divison(Calculator.java:28)
	at CalculatorTestSuccessful.testDivisionException(CalculatorTestSuccessful.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivisionException -->
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:CalculatorTestSuccessful@713064e8]" name="initCalculator" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
        <test-method status="FAIL" signature="testSubstraction()[pri:0, instance:CalculatorTestSuccessful@713064e8]" name="testSubstraction" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at CalculatorTestSuccessful.testSubstraction(CalculatorTestSuccessful.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSubstraction -->
        <test-method status="PASS" signature="testDivison()[pri:0, instance:CalculatorTestSuccessful@713064e8]" name="testDivison" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivison -->
        <test-method status="PASS" signature="afterEachTest()[pri:0, instance:CalculatorTestSuccessful@713064e8]" name="afterEachTest" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachTest -->
      </class> <!-- CalculatorTestSuccessful -->
    </test> <!-- testCaculate -->
    <test name="testMessagePrintout" duration-ms="52" started-at="2023-02-13T03:08:47Z" finished-at="2023-02-13T03:08:47Z">
      <class name="WelcomeMessageTest">
        <test-method status="PASS" signature="testBeforeClass()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testBeforeClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBeforeClass -->
        <test-method status="PASS" signature="testWelcomeMessagePage_001()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_001" duration-ms="4" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_001 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_002()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_002" duration-ms="2" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_002(WelcomeMessageTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_002 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_003()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_003" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_003 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_004()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_004" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_004(WelcomeMessageTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_004 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_005()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_005" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_005 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_006()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_006" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_006(WelcomeMessageTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_006 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_007()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_007" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_007 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_008()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_008" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_008(WelcomeMessageTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_008 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_009()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_009" duration-ms="10" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_009 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_010()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_010" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_010(WelcomeMessageTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_010 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_011()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_011" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_011 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_012()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_012" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_012(WelcomeMessageTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_012 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_013()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_013" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_013(WelcomeMessageTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_013 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_014()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_014" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_014 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_015()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_015" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_015 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_016()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_016" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_016 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_017()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_017" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_017(WelcomeMessageTest.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_017 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_018()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_018" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_018 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_019()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_019" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_019 -->
        <test-method status="FAIL" signature="testWelcomeMessagePage_020()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_020" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at WelcomeMessageTest.testWelcomeMessagePage_020(WelcomeMessageTest.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_020 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_021()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_021" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_021 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_022()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_022" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_022 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_023()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_023" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_023 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_024()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_024" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_024 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_025()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_025" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_025 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_026()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_026" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_026 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_027()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_027" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_027 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_028()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_028" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_028 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_029()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_029" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_029 -->
        <test-method status="PASS" signature="testWelcomeMessagePage_030()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testWelcomeMessagePage_030" duration-ms="1" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWelcomeMessagePage_030 -->
        <test-method status="PASS" signature="testAfterClass()[pri:0, instance:WelcomeMessageTest@62891fc8]" name="testAfterClass" is-config="true" duration-ms="2" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAfterClass -->
      </class> <!-- WelcomeMessageTest -->
    </test> <!-- testMessagePrintout -->
    <test name="TestClass" duration-ms="10020" started-at="2023-02-13T03:08:47Z" finished-at="2023-02-13T03:08:57Z">
      <class name="TestClass">
        <test-method status="PASS" signature="beforeTestTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="beforeTestTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestTestClass -->
        <test-method status="PASS" signature="beforeClassTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="beforeClassTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClassTestClass -->
        <test-method status="PASS" signature="beforeMethodWithParamTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="beforeMethodWithParamTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodWithParamTestClass -->
        <test-method status="PASS" signature="staticBeforeMethod()[pri:0, instance:TestClass@3d6a6bee]" name="staticBeforeMethod" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- staticBeforeMethod -->
        <test-method status="PASS" signature="unitLevel1TestClass()[pri:0, instance:TestClass@3d6a6bee]" name="unitLevel1TestClass" duration-ms="5006" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unitLevel1TestClass -->
        <test-method status="PASS" signature="beforeMethodTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="beforeMethodTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:47Z" finished-at="2023-02-13T08:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTestClass -->
        <test-method status="PASS" signature="afterMethodTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="afterMethodTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:52Z" finished-at="2023-02-13T08:38:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTestClass -->
        <test-method status="PASS" signature="beforeMethodWithParamTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="beforeMethodWithParamTestClass" is-config="true" duration-ms="1" started-at="2023-02-13T08:38:52Z" finished-at="2023-02-13T08:38:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodWithParamTestClass -->
        <test-method status="PASS" signature="beforeMethodTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="beforeMethodTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:52Z" finished-at="2023-02-13T08:38:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTestClass -->
        <test-method status="PASS" signature="unitLevel2TestClass()[pri:0, instance:TestClass@3d6a6bee]" name="unitLevel2TestClass" duration-ms="5008" started-at="2023-02-13T08:38:52Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unitLevel2TestClass -->
        <test-method status="PASS" signature="staticBeforeMethod()[pri:0, instance:TestClass@3d6a6bee]" name="staticBeforeMethod" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:52Z" finished-at="2023-02-13T08:38:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- staticBeforeMethod -->
        <test-method status="PASS" signature="afterTestTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="afterTestTestClass" is-config="true" duration-ms="2" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestTestClass -->
        <test-method status="PASS" signature="afterMethodTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="afterMethodTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTestClass -->
        <test-method status="PASS" signature="afterClassTestClass()[pri:0, instance:TestClass@3d6a6bee]" name="afterClassTestClass" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClassTestClass -->
      </class> <!-- TestClass -->
    </test> <!-- TestClass -->
    <test name="TestClassSecond" duration-ms="2" started-at="2023-02-13T03:08:57Z" finished-at="2023-02-13T03:08:57Z">
      <class name="TestClassSecond">
        <test-method status="FAIL" signature="beforeTestTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="beforeTestTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at TestClassSecond.beforeTestTestClassSecond(TestClassSecond.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestTestClassSecond -->
        <test-method status="SKIP" signature="staticBeforeMethodTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="staticBeforeMethodTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- staticBeforeMethodTestClassSecond -->
        <test-method status="SKIP" signature="beforeMethodWithParamTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="beforeMethodWithParamTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodWithParamTestClassSecond -->
        <test-method status="SKIP" signature="beforeMethodTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="beforeMethodTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTestClassSecond -->
        <test-method status="SKIP" signature="testUnitClassOne()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="testUnitClassOne" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnitClassOne -->
        <test-method status="SKIP" signature="beforeClassTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="beforeClassTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClassTestClassSecond -->
        <test-method status="SKIP" signature="afterMethodTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="afterMethodTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTestClassSecond -->
        <test-method status="SKIP" signature="afterMethodTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="afterMethodTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTestClassSecond -->
        <test-method status="SKIP" signature="beforeMethodTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="beforeMethodTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTestClassSecond -->
        <test-method status="SKIP" signature="afterTestTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="afterTestTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestTestClassSecond -->
        <test-method status="SKIP" signature="beforeMethodWithParamTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="beforeMethodWithParamTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodWithParamTestClassSecond -->
        <test-method status="SKIP" signature="staticBeforeMethodTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="staticBeforeMethodTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- staticBeforeMethodTestClassSecond -->
        <test-method status="SKIP" signature="testUnitClassTwo()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="testUnitClassTwo" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnitClassTwo -->
        <test-method status="SKIP" signature="afterClassTestClassSecond()[pri:0, instance:TestClassSecond@4b2e3e8f]" name="afterClassTestClassSecond" is-config="true" duration-ms="0" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClassTestClassSecond -->
      </class> <!-- TestClassSecond -->
    </test> <!-- TestClassSecond -->
    <test name="testOpenBrowserOnChrome" duration-ms="4425" started-at="2023-02-13T03:08:57Z" finished-at="2023-02-13T03:09:02Z">
      <class name="OpenBrowser">
        <test-method status="PASS" signature="openBrowserWithUrl()[pri:0, instance:OpenBrowser@29eda4f8]" name="openBrowserWithUrl" duration-ms="4425" started-at="2023-02-13T08:38:57Z" finished-at="2023-02-13T08:39:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowserWithUrl -->
      </class> <!-- OpenBrowser -->
    </test> <!-- testOpenBrowserOnChrome -->
    <test name="testGithub" duration-ms="0" started-at="2023-02-13T03:09:02Z" finished-at="2023-02-13T03:09:02Z">
    </test> <!-- testGithub -->
  </suite> <!-- Selenium-Test-cases -->
</testng-results>
